# Generated by Django 6.0.1 on 2026-02-02 03:00

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', upload_to=apps.users.models.user_avatar_path),
        ),
    ]
