# Generated by Django 5.2.11 on 2026-02-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
