# Generated by Django 6.0.1 on 2026-02-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('duration_days', models.DateTimeField()),
                ('max_people', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('DRAFT', 'Nhap'), ('ACTIVE', 'Kich hoat'), ('HIDDEN', 'An')], default='ACTIVE')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.categories')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.location')),
            ],
        ),
        migrations.CreateModel(
            name='TourSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateTimeField()),
                ('end_day', models.DateTimeField()),
                ('available_slots', models.IntegerField()),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tours')),
            ],
        ),
    ]
