# Generated by Django 5.2.11 on 2026-02-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourstop',
            name='tour',
        ),
        migrations.AddField(
            model_name='tourroute',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tourstop'),
        ),
        migrations.AlterField(
            model_name='tourroute',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
    ]
