# Generated by Django 6.0.1 on 2026-02-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tours_tourschedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
