# Generated by Django 6.0.1 on 2026-02-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tours_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='tours',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='tourschedules',
            old_name='tour_id',
            new_name='tour',
        ),
    ]
