# Generated by Django 6.0.1 on 2026-02-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('tours', '0005_rename_category_id_tours_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Tours',
            new_name='Tour',
        ),
        migrations.RenameModel(
            old_name='TourSchedules',
            new_name='TourSchedule',
        ),
    ]
