# Generated by Django 6.0.1 on 2026-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_rename_categories_category_rename_tours_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Kích hoạt'), ('HIDDEN', 'Ẩn')], default='ACTIVE'),
        ),
    ]
