# Generated by Django 6.0.1 on 2026-02-02 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0005_rename_category_id_tours_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_people', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Chua dat'), ('CONFIRMED', 'Da xac nhan'), ('CANCELLED', 'Da huy')], default='PENDING')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('tour_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourschedules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
