# Generated by Django 6.0.1 on 2026-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_bookings_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chưa đặt'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy')], default='PENDING'),
        ),
    ]
